### ISSUE TITLE
重新开始录制会覆盖掉之前的文件

### ISSUE THREAD

**Issue by zyyzcr** [Monibuca/plugin-record#19]
http://127.0.0.1:8080/record/api/start?type=flv&streamPath=live/test
然后
http://127.0.0.1:8080/record/api/stop?id=live/test/flv
再次开始录制
http://127.0.0.1:8080/record/api/start?type=flv&streamPath=live/test
test.flv会被覆盖

**Comment by langhuihui** [comment]
你可以设置分片模式就不会被覆盖了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月16日(周四) 下午5:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Monibuca/plugin-record] 重新开始录制会覆盖掉之前的文件 (Issue #19)




 
http://127.0.0.1:8080/record/api/start?type=flv&amp;streamPath=live/test
 然后
 http://127.0.0.1:8080/record/api/stop?id=live/test/flv
 再次开始录制
 http://127.0.0.1:8080/record/api/start?type=flv&amp;streamPath=live/test
 test.flv会被覆盖

**Comment by zyyzcr** [comment]
多谢
