### ISSUE TITLE
录制的视频文件没有文件名

### ISSUE THREAD

**Issue by lrqnew** [Monibuca/plugin-record#2]
发现以下几个问题：
1、录制的视频没有文件名；
2、同一个推流地址，再次录制就会覆盖之前的，希望加入时间戳命名

**Comment by langhuihui** [comment]
录制视频的文件名是根据streamPath而定的，例如streamPath=live/test则，在resource/live/test.flv
同一个推流地址，再次录制因为名称相同所以默认会进行覆盖，也可以选择append模式，进行追加。如果需要不同的文件名，则需要不同的推流地址。如果需要更复杂的逻辑，可以考虑二次开发。现有插件仅仅提供最基本的功能，起到演示的作用，实际需求千万化，需要创建适应业务需求的高度定制化插件。看懂现有的插件代码，则很容易自己开发新的插件。

**Comment by langhuihui** [comment]
已增加分片录制功能
