### ISSUE TITLE
录制下来的mp4文件，播放的时候需要全部加载完才能播放。

### ISSUE THREAD

**Issue by FireTiger23** [Monibuca/plugin-record#20]
录制下来的mp4文件，采用record插件进行点播的时候需要全部文件加载完毕才能开始播放。
当文件比较大的时候这个加载时间需要挺长时间的。

试过浏览器直接地址栏访问播放地址，还有video.js来播放均需要等文件全部加载完毕才能播放。

加载过程如下图。

![image](https://user-images.githubusercontent.com/6301010/229280082-7d090ed4-90f3-4623-91c4-82dbc2d6286e.png)

希望能帮忙解决下这个点播的问题。

**Comment by FireTiger23** [comment]
这个是需要全部加载完毕才能播放的视频信息
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/record/mp4/orig/c4d83347c15cb83a8747aa0948c9aa43/1680236980.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
  Duration: 01:00:00.78, start: 0.001000, bitrate: 2081 kb/s
  Stream #0:0[0x1](chi): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 143 kb/s (default)
    Metadata:
      handler_name    : mp4ff audio handler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](chi): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080, 1926 kb/s, 27.91 fps, 500 tbr, 1k tbn (default)
    Metadata:
      handler_name    : mp4ff video handler
      vendor_id       : [0][0][0][0]
      encoder         : mp4ff video packager






这个是可以边下边播的信息。
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/record/mp4/orig/c4d83347c15cb83a8747aa0948c9aa43/20-45-34.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2022-12-15T12:45:34.000000Z
  Duration: 00:55:02.50, start: 0.000000, bitrate: 1889 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 143 kb/s (default)
    Metadata:
      creation_time   : 2022-12-15T12:45:34.000000Z
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1920x1080, 1736 kb/s, 25.50 fps, 500 tbr, 1k tbn (default)
    Metadata:
      creation_time   : 2022-12-15T12:45:34.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]

**Comment by afly3** [comment]
ffmpeg -i input.mp4 -movflags faststart -acodec copy -vcodec copy output.mp4
录制完以后，把moov从文件尾部转移到文件头部，就不用播放时再加载全部文件了。
