### ISSUE TITLE
录制文件播放时的时长问题

### ISSUE THREAD

**Issue by YOLO-PK** [Monibuca/plugin-record#23]
录制MP4文件无时长
![image](https://user-images.githubusercontent.com/130424874/233815374-57aaa54e-0958-458c-abab-876759a69e3c.png)

**Comment by langhuihui** [comment]
> fMP4（Fragmented mp4）
> fMP4 跟普通 mp4 基本文件结构是一样的。普通mp4用于点播场景，fmp4通常用于直播场景。
> 
> 它们有以下差别：
> 
> 普通mp4的时长、内容通常是固定的。fMP4 时长、内容通常不固定，可以边生成边播放；
> 普通mp4完整的metadata都在moov里，需要加载完moov box后，才能对mdat中的媒体数据进行解码渲染；
> fMP4中，媒体数据的metadata在moof box中，moof 跟 mdat （通常）结对出现。moof 中包含了sample duration、sample size等信息，因此，fMP4可以边生成边播放；

录制文件采用的是fmp4格式，非传统mp4格式，所以没有时长

**Comment by YOLO-PK** [comment]
ok
