### ISSUE TITLE
录制文件保存0kb

### ISSUE THREAD

**Issue by echome123** [Monibuca/plugin-record#26]
最新版本的录制使用过程中，发现录制文件没有落盘成功，手动查看了一下录制过程：
当录制开始时候，状态一切正常，文件大小也在逐步增加。
但是当录制的流断开后，这个录制文件就变成0kb大小了，没有任何内容。
以下是执行过程的日志（录制插件开启了分片录制）：

> 开始录制：
[start.txt](https://github.com/Monibuca/plugin-record/files/11351688/start.txt)

> 结束录制：
[end.txt](https://github.com/Monibuca/plugin-record/files/11351691/end.txt)

发现该问题后，切换回以前的老版本就恢复正常了，不知道是什么问题

**Comment by langhuihui** [comment]
看上去是由于写入元数据导致的

**Comment by langhuihui** [comment]
你是什么操作系统

**Comment by echome123** [comment]
> 你是什么操作系统

@langhuihui Ubuntu 20.04.5

**Comment by echome123** [comment]
大佬，看到有新版本发布了，是不是已经修复了

**Comment by langhuihui** [comment]
我本地没有复现出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月30日(周日) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Monibuca/plugin-record] 录制文件保存0kb (Issue #26)




 
大佬，看到有新版本发布了，是不是已经修复了
