### ISSUE TITLE
ts切片时长问题

### ISSUE THREAD

**Issue by stdawn** [Monibuca/plugin-record#27]
设置 
   hls:
     autorecord: true
     fragment: 10s
但保存的ts切片为8s, ts文件间隔是10s
![image](https://github.com/Monibuca/plugin-record/assets/13537943/eba463a6-34d4-4e2c-a297-624a1be2f382)

![image](https://github.com/Monibuca/plugin-record/assets/13537943/5b1f80b6-2dbd-42ed-8497-48039e89acdd)
那每个ts丢失了2秒？

**Comment by stdawn** [comment]
把 fragment: 设置为20s, 切片也只有18s

**Comment by LookUpPls** [comment]
应该是在等I帧吧 ， 要不然会花屏。  我录制的就是多两秒

**Comment by langhuihui** [comment]
可以自己看源码，调试一下，代码很简单

**Comment by langhuihui** [comment]
修复于：v4.4.5-0.20231107053326-a0d5b146e9c4
