### ISSUE TITLE
录像在线不能点播

### ISSUE THREAD

**Issue by zzs89117920** [Monibuca/plugin-record#28]
windows平台的安装版本（m7s_4.6.4_windows_amd64），用obs推流，可以正常观看，开启录像后，也生成文件了
![image](https://github.com/Monibuca/plugin-record/assets/5515847/693ee0e2-efb5-46bf-be96-37ce04843286)
![image](https://github.com/Monibuca/plugin-record/assets/5515847/6c1cfe72-0829-4449-8b3a-573b355b5c89)
可是用http://localhost:8080/record/live/test.flv地址不能播放
![image](https://github.com/Monibuca/plugin-record/assets/5515847/a9368304-ba5d-4b54-b43b-5eeb1d166d65)

**Comment by langhuihui** [comment]
播放的时候地址是录像的文件地址，不再是live/test，而是live/test/xxxxxxxx.flv

**Comment by zzs89117920** [comment]
> 播放的时候地址是录像的文件地址，不再是live/test，而是live/test/xxxxxxx.flv

好的，谢谢，好使了
