### ISSUE TITLE
当前的v4.4.3录制hls是不是有问题

### ISSUE THREAD

**Issue by zxfskr** [Monibuca/plugin-record#30]
我对go不熟，看了下源码好像是没有去调用m3u8的文件生成接口，导致write函数是空指针

请求
http://127.0.0.1:8080/record/api/start?type=hls&streamPath=live/test&fragment=10s

2023/09/21 10:40:24 http: panic serving 127.0.0.1:62042: runtime error: invalid memory address or nil pointer dereference
goroutine 84 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1868 +0xb9
panic({0x136cfe0?, 0x23e92d0?})
        C:/Program Files/Go/src/runtime/panic.go:920 +0x270
m7s.live/plugin/hls/v4.(*Playlist).WriteInf(0xc0000e6700, {0x0, {0xc002cf2630, 0xd}, {0x0, 0x0}})
        C:/workspace/monibuca/vendor/m7s.live/plugin/hls/v4/hls.go:70 +0xbe
m7s.live/plugin/record/v4.(*HLSRecorder).CreateFile(0xc0000e6700)
        C:/workspace/monibuca/vendor/m7s.live/plugin/record/v4/hls.go:114 +0x507
m7s.live/plugin/record/v4.(*HLSRecorder).OnEvent(0xc0000e6700, {0x1455140?, 0xc0000e6700?})
        C:/workspace/monibuca/vendor/m7s.live/plugin/record/v4/hls.go:51 +0x2a6
m7s.live/engine/v4.(*IO).receive.func2()
        C:/workspace/monibuca/vendor/m7s.live/engine/v4/io.go:252 +0x3e
m7s.live/engine/v4.(*IO).receive(0xc0000e6858, {0xc0002b80ca?, 0x635b9c8?}, {0x1462f8c8940?, 0xc0000e6700})
        C:/workspace/monibuca/vendor/m7s.live/engine/v4/io.go:276 +0x1c32
m7s.live/engine/v4.(*Subscriber).Subscribe(...)
        C:/workspace/monibuca/vendor/m7s.live/engine/v4/subscriber.go:128
m7s.live/engine/v4.(*Plugin).Subscribe(0x0?, {0xc0002b80ca, 0x9}, {0x1462f8c8858, 0xc0000e6700})
        C:/workspace/monibuca/vendor/m7s.live/engine/v4/plugin.go:306 +0xe8
m7s.live/plugin/record/v4.(*Recorder).start(0xc0000e6858, {0x1d2b848?, 0xc0000e6700}, {0xc0002b80ca, 0x9}, 0x0)
        C:/workspace/monibuca/vendor/m7s.live/plugin/record/v4/subscriber.go:72 +0x66
m7s.live/plugin/record/v4.(*HLSRecorder).Start(0xc0000e6700, {0xc0002b80ca, 0x9})
        C:/workspace/monibuca/vendor/m7s.live/plugin/record/v4/hls.go:33 +0x7f
m7s.live/plugin/record/v4.(*RecordConfig).API_start(0x245a8e0?, {0x1d1bd90, 0xc000444000}, 0xc0002f2800)
        C:/workspace/monibuca/vendor/m7s.live/plugin/record/v4/restful.go:84 +0x6a2
net/http.HandlerFunc.ServeHTTP(0xc0002b80a4?, {0x1d1bd90?, 0xc000444000?}, 0x7?)
        C:/Program Files/Go/src/net/http/server.go:2136 +0x29
m7s.live/engine/v4.(*Plugin).handle.(*Plugin).logHandler.func2({0x1d1bd90, 0xc000444000}, 0xc0002f2800)
        C:/workspace/monibuca/vendor/m7s.live/engine/v4/plugin.go:79 +0x334
net/http.HandlerFunc.ServeHTTP(0x1403b00?, {0x1d1bd90?, 0xc000444000?}, 0x1d11f70?)
        C:/Program Files/Go/src/net/http/server.go:2136 +0x29
m7s.live/engine/v4/config.(*HTTP).Handle.CORS.func1({0x1d1bd90, 0xc000444000}, 0xc0002f2800)
        C:/workspace/monibuca/vendor/m7s.live/engine/v4/util/socket.go:164 +0x157
net/http.HandlerFunc.ServeHTTP(0xca6380?, {0x1d1bd90?, 0xc000444000?}, 0xf5109a?)
        C:/Program Files/Go/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0x245a820?, {0x1d1bd90, 0xc000444000}, 0xc0002f2800)
        C:/Program Files/Go/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0xc006ba86c0?}, {0x1d1bd90?, 0xc000444000?}, 0x6?)
        C:/Program Files/Go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc000a006c0, {0x1d1dbb8, 0xc000295a10})
        C:/Program Files/Go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 19
        C:/Program Files/Go/src/net/http/server.go:3086 +0x5cb

**Comment by langhuihui** [comment]
确实有问题，下一个版本修复
