### ISSUE TITLE
录制视频stop的问题

### ISSUE THREAD

**Issue by zxfskr** [Monibuca/plugin-record#31]
我看到停止录制stop接口后没有调用file close，再次调用start会报任务已存在，这样会不会导致文件描述符泄露啊，还是说go应该自己gc掉文件描述符？
12:00:43	ERROR	创建文件	{"流": "live/test", "类型": "HLSRecorder", "ID": "live/test/hls", "path": "live\\test.m3u8", "error": "recorder exist"}
12:00:43	INFO	停止	{"流": "live/test", "类型": "HLSRecorder", "ID": "live/test/hls", "error": "recorder exist"}
12:00:43	ERROR	play	{"流": "live/test", "类型": "HLSRecorder", "ID": "live/test/hls", "error": "context canceled"}

**Comment by langhuihui** [comment]
升级一下版本，engine 中的一个问题
