### ISSUE TITLE
录制HLS转TS保存之后的播放问题

### ISSUE THREAD

**Issue by Arbureva** [Monibuca/plugin-record#32]
客户端断开后，录制的文件可以播放，但是出现了些问题，VLC播放有声音没有连续视频帧，哔哩哔哩播放器播放有声音有连续视频帧但是视频帧画质极低，Windows播放器播放有连续且高清的视频帧但是没有连续的声音

**Comment by Arbureva** [comment]
我又试了一遍，这次FLV播放可以连续播放视频帧，但是不能播放声音，B站播放器还是一样都正常，但是画质极低

**Comment by langhuihui** [comment]
第二次你是录制了 flv 格式？

**Comment by Arbureva** [comment]
不是，第二次也是ts格式

**Comment by Arbureva** [comment]
VLC播放，我说错了

**Comment by Arbureva** [comment]
![image](https://github.com/Monibuca/plugin-record/assets/96331179/87d733ab-fea2-426e-8289-c4de10bb58f0)
然后有个问题，就是m3u8文件内容好像是空的？这样是否会影响在线播放

**Comment by Arbureva** [comment]
> ![image](https://user-images.githubusercontent.com/96331179/279293765-87d733ab-fea2-426e-8289-c4de10bb58f0.png) 然后有个问题，就是m3u8文件内容好像是空的？这样是否会影响在线播放

这个怎么说呢，是覆盖的，同一个streampath推流后是会覆盖，直接丢失上一个了，不过这个问题我再正式环境下不会出现了，只不过m3u8的格式是这样的吗？还是因为我录制的时间不够长才导致里面只有一个文件？

**Comment by langhuihui** [comment]
确实是覆盖的，你可以通过指定文件名方式，防止覆盖

**Comment by Locter9001** [comment]
> 确实是覆盖的，你可以通过指定文件名方式，防止覆盖
好的，我线上不会有这种问题，我先躲测一下这个播放问题

**Comment by Arbureva** [comment]
> 确实是覆盖的，你可以通过指定文件名方式，防止覆盖

好的，我线上不会有这种问题，我先躲测一下这个播放问题

**Comment by Arbureva** [comment]
经过测试，播放是没有问题的，不要使用 VLC 和 其他播放器播放，直接用 `ffmpeg` 的 `ffplay` 套件播放，示例如下：
```shell
ffplay ./hhh.m3u8
```

> 效果超级好！非常流畅而且高清

**Comment by langhuihui** [comment]
vlc 里面有一个 crc 验证，没有通过，这个我一直没解决
