### ISSUE TITLE
后续会支持分布式存储系统吗？

### ISSUE THREAD

**Issue by ChenWK20** [Monibuca/plugin-record#9]
比如录制视频时，文件保存到分布式存储MinIO，或者点播时从MinIO读取文件。

**Comment by langhuihui** [comment]
已经预留了创建文件的接口，目前需要自己去实现一个插件，可以复用现有的录像插件的代码，然后用自己的创建文件的方法覆盖默认的方法，因为这个涉及到代码，没有办法做成配置文件

**Comment by dwdcth** [comment]
可以参考 #12 ，自定义存储到minio
